[project]
name = "eagleeye"
version = "0.1.0"
description = "GCS for interacting with SteelEagle vehicles."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.119.0",
    "uvicorn>=0.38.0",
]
