[project]
name = "ideal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "grpcio",
    "grpcio-tools",
    "pyzmq>=27.1.0",
    "numpy",
    "pillow>=12.0.0",
]
