name: Build and push avoidance engine

on:
  push:
    branches: [ "main", "dev" ]
    tags: [ "v*" ]
    paths:
      - '.github/workflows/build-avoidance-engine.yml'
      - 'backend/server/engines/avoidance/**'
jobs:
  build-and-push:
    uses: ./.github/workflows/deploy-docker-img.yml
    with:
      name: steeleagle-avoidance-engine
      dockerfile: backend/server/engines/avoidance/Dockerfile
    secrets: inherit
