[vehicle]
name = '<NAME>'
kwargs = {}

[cloudlet]
swarm_controller = '<SWARM_CONTROLLER>:5003'
remote_compute_service = '<GABRIEL>:9099'

[logging]
# Whether or not to create an MCAP flight log for mission replay
generate_flight_log = true
# Log to a custom filename; otherwise will autogenerate
# a name based on name, date, and time if empty string
# is provided
custom_filename = '' 
# Path to log file
file_path = 'logger/logs'
# Log level
log_level = 'DEBUG'
